### ISSUE TITLE
GPS 2 Sensor from Power Box to implement

### ISSUE THREAD

**Issue by hanskranzler** [RealTadango/FrSky#2]
Hello Real Tadango
Would it be possible to change the program so that only the GPS2 sensor works.
It is the best GPS sensor for a jet.
It is also a log how far and how high was flown, a problem on our airfield.
![9710298_powerbox-systems-gps-ii-powerbox](https://user-images.githubusercontent.com/37708957/37846468-f9c84e86-2ecd-11e8-88e4-d85b0c74525f.jpg)
Best regards
Hans Kranzler

**Comment by RealTadango** [comment]
Yes i will create a sensor for that. I already ordered a PB GPS 2 for that. The FrSky GPS sensor is fun but far from accurate.....

**Comment by hanskranzler** [comment]
Great.

**Comment by hanskranzler** [comment]
Hello
How is the status?

**Comment by RealTadango** [comment]
I received the PB GPS 2 yesterday and will be building my new development machine tomorrow. After that i can start to see what the sensor outputs. The converter will then ready soon but the conversion of the locations will take a bit more time.

**Comment by RealTadango** [comment]
It took a while, but the powerbox code works for a GPS module only now. The coordinates are correct to. It will simply relay the values it gets from a powerbox device. The GPS module must be configured for powerbox usage.
